---
- name: Manage Security Group
  ec2_group:
    name: '{{ cloud_securitygroup_name }}'
    description: '{{ cloud_securitygroup_name }}'
    region: '{{ cloud_securitygroup_region }}'
    state: '{{ cloud_securitygroup_state|default("present") }}'
