---
- name: Manage Security Group
  vr_firewall_group:
    name: '{{ cloud_securitygroup_name }}'
    state: '{{ cloud_securitygroup_state|default("present") }}'

- name: Manage Security group's firewall rule
  vr_firewall_rule:
    group: '{{ cloud_securitygroup_name }}'
    protocol: '{{ item.proto }}'
    start_port: '{{ item.from_port }}'
    end_port: '{{ item.to_port }}'
    cidr: '{{ item.cidr_ip }}'
    state: '{{ item.state|default("present") }}'
  with_items: '{{ cloud_securitygroup_rules }}'
  when: cloud_securitygroup_state|default("present") == 'present'
