---
- name: Manage Security Group
  vr_firewall_group:
    name: '{{ cloud_securitygroup_name }}'
    state: '{{ cloud_securitygroup_state|default("present") }}'

- name: Manage Security group's firewall rule
  vr_firewall_rule:
    group: '{{ cloud_securitygroup_name }}'
    protocol: '{{ rule.proto }}'
    start_port: '{{ rule.from_port }}'
    end_port: '{{ rule.to_port }}'
    cidr: '{{ rule.cidr_ip }}'
    state: '{{ rule.state|default("present") }}'
  loop: '{{ cloud_securitygroup_rules }}'
  loop_control:
    loop_var: rule
  when: cloud_securitygroup_state|default("present") == 'present'
