---
- name: Manage Security Group
  os_security_group:
    name: '{{ cloud_securitygroup_name }}'
    region_name: '{{ cloud_security_region|default(None) }}'
    state: '{{ cloud_securitygroup_state|default("present") }}'

- name: Manage Security group's firewall rule
  os_security_group_rule:
    security_group: '{{ cloud_securitygroup_name }}'
    protocol: '{{ rule.proto }}'
    port_range_min: '{{ rule.from_port }}'
    port_range_max: '{{ rule.to_port }}'
    remote_ip_prefix: '{{ rule.cidr_ip }}'
    state: '{{ rule.state|default("present") }}'
  loop: '{{ cloud_securitygroup_rules }}'
  loop_control:
    loop_var: rule
  when: cloud_securitygroup_state|default("present") == 'present'
